on: 
  push:
    branches:
    - 22
name: Deploy to Test Site
jobs:
  deployToTest:
    name: Deploy to Test Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set Up Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.13'
    - run: npm run-script build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - run: aws s3 cp /home/runner/work/parks-and-refuges-fev/parks-and-refuges-fev/build/ s3://test.wim.usgs.gov/pNrFEV-dev/ --recursive
    - name: GitHub Action for Slack
      uses: Ilshidur/action-slack@9273a03
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      with:
        args: "Successfully deployed to test.wim.usgs.gov/pNrFEV-dev"
